# Generated by Django 4.2.28 on 2026-02-08 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionCesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_desembolso', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('monto_total_facturas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tasa_descuento', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_a_desembolsar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('desembolsada', 'Desembolsada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturas.factura')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.operacioncesion')),
            ],
        ),
        migrations.AddField(
            model_name='operacioncesion',
            name='facturas',
            field=models.ManyToManyField(related_name='operaciones', through='operaciones.OperacionFactura', to='facturas.factura'),
        ),
        migrations.AddConstraint(
            model_name='operacionfactura',
            constraint=models.UniqueConstraint(fields=('operacion', 'factura'), name='uq_operacion_factura'),
        ),
        migrations.AddIndex(
            model_name='operacioncesion',
            index=models.Index(fields=['estado'], name='operaciones_estado_0117da_idx'),
        ),
        migrations.AddIndex(
            model_name='operacioncesion',
            index=models.Index(fields=['fecha_solicitud'], name='operaciones_fecha_s_cd24ba_idx'),
        ),
    ]
