# Generated by Django 4.2.28 on 2026-02-08 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creada', 'Creada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('desembolsada', 'Desembolsada'), ('finalizada', 'Finalizada'), ('error', 'Error')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=20)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operaciones.operacioncesion')),
            ],
            options={
                'indexes': [models.Index(fields=['tipo'], name='operaciones_tipo_87151e_idx'), models.Index(fields=['fecha'], name='operaciones_fecha_7f9dbc_idx')],
            },
        ),
    ]
