# Generated by Django 4.2.28 on 2026-02-07 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('giro', models.CharField(blank=True, default='', max_length=255)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('linea_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('linea_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='clientes_cl_estado_54796b_idx'), models.Index(fields=['linea_credito'], name='clientes_cl_linea_c_75baa6_idx')],
            },
        ),
    ]
