# Generated by Django 4.2.28 on 2026-02-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('rut_deudor', models.CharField(max_length=12)),
                ('razon_social_deudor', models.CharField(max_length=255)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En proceso'), ('cedida', 'Cedida'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='disponible', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='facturas_fa_estado_de2e38_idx'), models.Index(fields=['rut_deudor'], name='facturas_fa_rut_deu_20aa5a_idx'), models.Index(fields=['fecha_emision'], name='facturas_fa_fecha_e_6a1db1_idx'), models.Index(fields=['fecha_vencimiento'], name='facturas_fa_fecha_v_c2133c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('cliente', 'numero_factura'), name='uq_factura_cliente_numero'),
        ),
    ]
